Use the subdomain to select country
openfoodfacts/openfoodfacts-hungergames-react pull request #25
Opened 2019-06-07 17:39 UTC by hangy

Use the OFF subdomain to determine the initial country to select from the dropdown.

Fixes #19

2019-06-10 16:45 UTC, ArnaudBarre reviewed
Thank for fixing this by yourself !

I think you can merge this PR and closed the two others.

I added two minor feedback.

A change that could be good for others is to avoid `lc` and `cc` abbreviations, this makes the code less readable I found

2019-06-10 16:45 UTC, ArnaudBarre commented on src/Questions/index.js
> +        {Object.entries(countries).map(([_, value]) => (
Like countries is a list now you can simplify with:
`{countries.map(country =>` or `{countries.map(({ id, label }) =>` if you like destructuring like me :)

2019-06-10 16:45 UTC, ArnaudBarre commented on src/Questions/index.js
>    })();
I should have done this before but if you can put this function outside of the component render, no need to do it each time :)

2019-06-10 17:56 UTC, hangy commented on src/Questions/index.js
> +        {Object.entries(countries).map(([_, value]) => (
Thanks, fixed in 183634552d6ab514eb542c236bc8ba5b063f0bf7.

2019-06-10 17:57 UTC, hangy commented on src/Questions/index.js
>    })();
True, that's a bit redundant since the subdomain shouldn't really change after the site was loaded (or we wouldn't care). Fixed in 3be24fd3b4edbcfe49f99e3bd6bd5a66e2cbb4ed.

2019-06-10 17:57 UTC, hangy commented
Thanks for your feedback, @ArnaudBarre! I've addressed your comments and updated the PR accordingly.

2019-06-11 08:19 UTC, ArnaudBarre approved these changes
Looks great! There is a little console.log left but it's not harmful ;)

2019-06-11 08:25 UTC, hangy commented
>There is a little console.log left but it's not harmful ;)

How did I miss that? :confused: :smile:

2019-06-11 13:34 UTC, VaiTon requested changes
😄

2019-06-11 13:34 UTC, VaiTon commented on src/Questions/index.js
> +  console.log(window.location.href);
Remove this console.log

2019-06-11 14:34 UTC, merged

2019-06-11 14:35 UTC, ArnaudBarre commented
Oh effectively GitHub considered the two other PRs merged, I didn't know about his feature :)